sudo: requiered
dist: trusty

language: java
jdk: oraclejdk8

env:
    - COVERAGE=0.24 TARGET=./monolithic/ui
    - COVERAGE=0.24 TARGET=./monolithic/service/cart
    - COVERAGE=0.24 TARGET=./monolithic/service/user
    - COVERAGE=0.24 TARGET=./monolithic/repository/order
    - COVERAGE=0.24 TARGET=./monolithic/repository/cart
    - COVERAGE=0.24 TARGET=./monolithic/repository/product
    - COVERAGE=0.31 TARGET=./monolithic/repository/user

install:
  - "./gradlew clean jar"

script:
  # Run ANSIBLE checks
  # - ANSIBLE0008: Disabled for use of sudo warnings - to address
  # - ANSIBLE0011: Disabled for all tasks which should be named
  # - ANSIBLE0012: Disabled (should not change if nothings needs doing) - to address
  # - ANSIBLE0013: Disabled - few uses of shell commands - to address
  #- find vagrant/provision -name "*.yml" -exec ansible-lint -x ANSIBLE008,ANSIBLE0011,ANSIBLE0012,ANSIBLE0013  {} +
  #- "./gradlew test"
  - "COVERAGE=$COVERAGE ./gradlew -p $TARGET check"

deploy:
  provider: script
  script: echo 'WIP'
  on:
    all_branches: true
