sudo: requiered
dist: trusty

language: java
jdk:
  - oraclejdk8
  - oraclejdk9

services:
  - docker

env:
    - COVERAGE=0.057 TARGET=./monolithic/ui
    - COVERAGE=0.148 TARGET=./monolithic/service/cart
    - COVERAGE=0.0 TARGET=./monolithic/service/user
    - COVERAGE=0.36 TARGET=./monolithic/repository/order
    - COVERAGE=0.0 TARGET=./monolithic/repository/cart
    - COVERAGE=0.124 TARGET=./monolithic/repository/product
    - COVERAGE=0.31 TARGET=./monolithic/repository/user

install:
  - "./gradlew clean jar"

script:
  # Run ANSIBLE checks
  # - ANSIBLE0008: Disabled for use of sudo warnings - to address
  # - ANSIBLE0011: Disabled for all tasks which should be named
  # - ANSIBLE0012: Disabled (should not change if nothings needs doing) - to address
  # - ANSIBLE0013: Disabled - few uses of shell commands - to address
  #- find vagrant/provision -name "*.yml" -exec ansible-lint -x ANSIBLE008,ANSIBLE0011,ANSIBLE0012,ANSIBLE0013  {} +
  #- "./gradlew test"
  - "COVERAGE=$COVERAGE ./gradlew -p $TARGET check"

before_deploy:
  - "./gradlew -p ./monolithic/ui packageToContainer"

deploy:
  provider: script
  script: "chmod +x ./script/deploy.sh && ./script/deploy.sh"
  on:
    all_branches: true
